kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  labels:
    build: custom-nginx
  name: build-custom-nginx
spec:
  source:
    git:
      uri: 'https://github.com/aushacker/general-tips-tools.git'
    contextDir: nginx
    type: Git
  output:
    to:
      kind: ImageStreamTag
      name: custom-nginx:latest
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
      imageOptimizationPolicy: SkipLayers
    type: Docker
