apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: ''
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-db
  labels:
    app.openshift.io/runtime: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: postgres
        image: 'image-registry.openshift-image-registry.svc:5000/openshift/postgresql:13-el8'
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRESQL_USER
          value: sonarUser
        - name: POSTGRESQL_PASSWORD
          value: sonarPass
        - name: POSTGRESQL_DATABASE
          value: sonarDB
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/pgsql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-data
