kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: sonarqube
  labels:
    app: sonarqube
spec:
  host: sonarqube.apps-crc.testing
  to:
    kind: Service
    name: sonarqube
    weight: 100
  port:
    targetPort: 9000
  wildcardPolicy: None
