apiVersion: v1
kind: ConfigMap
metadata:
  name: maven-settings
data:
  settings.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <settings>
      <mirrors>
        <mirror>
          <id>central</id>
          <name>Maven Central Respository</name>
          <url>https://repo1.maven.org/maven2/</url>
          <mirrorOf>central</mirrorOf>
        </mirror>
        <mirror>
          <id>redhat-ga</id>
          <name>Red Hat Respository</name>
          <url>https://maven.repository.redhat.com/ga/all/</url>
          <mirrorOf>redhat</mirrorOf>
        </mirror>
      </mirrors>
    </settings>
