apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases: 
- ../../base

commonLabels:
  env: dev

namePrefix: dev-

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: my-java-server-env-vars
  behavior: merge
  literals:
  - JAVA_TOOL_OPTIONS=-agentlib:hprof more values
  - JAVA_FLAG=xyz
