apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: java-ci
spec:
  params: 
    - name: deployment-name
      type: string
      description: name of the deployment to be patched
    - name: git-url
      type: string
      description: Repository URL to clone from
    - name: git-revision
      type: string
      description: Revision to checkout (branch, tag, sha, ref etc.)
      default: 'main'
    - name: context-dir
      type: string
      description: The context directory within the repository for sources on which we want to execute maven goals
      default: '.'
    - name: IMAGE
      type: string
      description: image to be built from the code
  tasks: 
    - name: git-clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: maven-build
      taskRef:
        name: mvn
#        name: maven
#        kind: ClusterTask
      runAfter:
        - git-clone
      params:
        - name: CONTEXT_DIR
          value: $(params.context-dir)
        - name: GOALS
          value:
            - -DskipTests
            - --batch-mode
            - clean
            - package
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: maven-settings
          workspace: maven-settings
        - name: maven-repo
          workspace: maven-repo
  workspaces: 
    - name: shared-workspace
    - name: maven-settings
    - name: maven-repo
