apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: my-java-server-env-vars
  behavior: merge
  literals:
  - REGION=emea
