apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  channel: helm-test/bitnami-charts
  name: jenkins
  packageFilter:
    version: 10.2.4         # NB. must match version: in index.yaml (not appVersion:)
  packageOverrides:
    - packageAlias: jenkins
      packageName: jenkins
  placement:
    placementRef:
      kind: PlacementRule
      name: jenkins
  secondaryChannel: ''
