apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: junk

resources:
- service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: my-java-server-props
  files:
  - application.properties
- name: my-java-server-env-vars
  literals: 
  - JAVA_HOME=/opt/java/jdk
  - JAVA_TOOL_OPTIONS=-agentlib:hprof
