apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep-request
  labels:
    app: sleep-request
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep-request
  template:
    metadata:
      labels:
        app: sleep-request
    spec:
      containers:
      - name: sleep-request
        image: registry.access.redhat.com/ubi8/ubi:latest
        resources:
          requests:
            cpu: '50m'
            memory: '64Mi'
        command:
          - /bin/bash
          - -c
          - 'sleep 300'
