apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mongodb

commonLabels:
  app: mongodb

resources:
  - namespace.yaml
  - pv.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: mongodb
    newName: mongo
    newTag: 'latest'
