apiVersion: batch/v1
kind: Job
metadata:
  generateName: podman-version-
spec:
  template:
    spec:
      serviceAccountName: mybuilder
      securityContext:
        runAsUser: 1000
      containers:
      - name: podman-version
        image: quay.io/sdavies/mypodman:latest
        imagePullPolicy: IfNotPresent
        command:
        - podman
        - version
      restartPolicy: Never
